steps:
  # Build Docker image
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "--build-arg",
        "NEXT_PUBLIC_CONVEX_URL=${_CONVEX_URL}",
        "-t",
        "gcr.io/$PROJECT_ID/eventflow:latest",
        ".",
      ]

  # Push to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/eventflow:latest"]

  # Run Prisma database migrations
  - name: "gcr.io/$PROJECT_ID/eventflow:latest"
    entrypoint: "npx"
    args: ["prisma", "migrate", "deploy"]
    env:
      - "DATABASE_URL=${_DATABASE_URL}"

  # Deploy to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "eventflow"
      - "--image"
      - "gcr.io/$PROJECT_ID/eventflow:latest"
      - "--region"
      - "europe-west1"
      - "--platform"
      - "managed"
      - "--allow-unauthenticated"
      - "--port"
      - "8080"
      - "--memory"
      - "512Mi"
      - "--min-instances"
      - "0"
      - "--max-instances"
      - "3"
      - "--set-env-vars"
      - "DATABASE_URL=${_DATABASE_URL},AUTH_SECRET=${_NEXTAUTH_SECRET},NEXTAUTH_SECRET=${_NEXTAUTH_SECRET},AUTH_URL=${_NEXTAUTH_URL},NEXTAUTH_URL=${_NEXTAUTH_URL},AUTH_TRUST_HOST=true,NEXT_PUBLIC_CONVEX_URL=${_CONVEX_URL},RESEND_API_KEY=${_RESEND_API_KEY},GOOGLE_CLIENT_ID=${_GOOGLE_CLIENT_ID},GOOGLE_CLIENT_SECRET=${_GOOGLE_CLIENT_SECRET},APPLE_CLIENT_ID=${_APPLE_CLIENT_ID},APPLE_CLIENT_SECRET=${_APPLE_CLIENT_SECRET},APPLE_TEAM_ID=${_APPLE_TEAM_ID},APPLE_KEY_ID=${_APPLE_KEY_ID}"

substitutions:
  _DATABASE_URL: ""
  _CONVEX_URL: ""
  _NEXTAUTH_SECRET: "2Oi9lWVtY8HyJLtLSz1zwa+bOp20GiCH96ASwaLPAJ8="
  _NEXTAUTH_URL: "https://eventflow-ga.web.app"
  _GOOGLE_CLIENT_ID: ""
  _GOOGLE_CLIENT_SECRET: ""
  _APPLE_CLIENT_ID: ""
  _APPLE_CLIENT_SECRET: ""
  _APPLE_TEAM_ID: ""
  _APPLE_KEY_ID: ""
  _RESEND_API_KEY: ""

images:
  - "gcr.io/$PROJECT_ID/eventflow:latest"

options:
  logging: CLOUD_LOGGING_ONLY
